<?php get_header(); ?>
<section class="ya-hero ya-home-hero">
  <div class="ya-hero-mesh" aria-hidden="true"></div>
  <div class="ya-shell ya-hero-layout">
    <div class="ya-hero-copy reveal">
      <span class="ya-kicker"><?php echo esc_html(ya_t('hero_kicker')); ?></span>
      <h1><?php echo esc_html(ya_t('hero_title')); ?></h1>
      <p><?php echo esc_html(ya_t('hero_text')); ?></p>
      <div class="ya-actions"><a class="ya-btn" href="<?php echo esc_url(ya_page('services')); ?>"><?php echo esc_html(ya_t('hero_cta')); ?></a><a class="ya-btn ya-btn-outline" href="<?php echo esc_url(ya_page('demander-un-devis')); ?>"><?php echo esc_html(ya_t('hero_quote')); ?></a></div>
      <div class="ya-trust-row"><span><i class="fa-solid fa-bolt"></i><?php echo esc_html(ya_t('response')); ?></span><span><i class="fa-solid fa-certificate"></i><?php echo esc_html(ya_t('certified')); ?></span><span><i class="fa-solid fa-location-dot"></i><?php echo esc_html(ya_t('coverage')); ?></span></div>
    </div>
    <div class="ya-network-visual reveal" data-ya-parallax>
      <div class="ya-network-glow"></div>
      <div class="ya-network-ring r1"></div><div class="ya-network-ring r2"></div><div class="ya-network-ring r3"></div>
      <div class="ya-network-core"><i class="fa-solid fa-cloud"></i><small>SECURE CLOUD</small></div>
      <div class="ya-network-node n1"><i class="fa-solid fa-server"></i><span>Infrastructure</span></div>
      <div class="ya-network-node n2"><i class="fa-solid fa-shield-halved"></i><span>Security</span></div>
      <div class="ya-network-node n3"><i class="fa-solid fa-wifi"></i><span>Networks</span></div>
      <div class="ya-network-node n4"><i class="fa-solid fa-laptop"></i><span>Support</span></div>
      <svg viewBox="0 0 620 520" aria-hidden="true"><path d="M120 270C205 140 400 115 505 260"/><path d="M105 300C220 390 400 405 525 290"/><path d="M310 90V440"/><path d="M125 150L500 390"/><path d="M505 145L120 390"/></svg>
    </div>
  </div>
  <div class="ya-hero-bottom"><div class="ya-shell"><span><strong>Microsoft 365</strong> workplace</span><span><strong>Networks</strong> & Wi‑Fi</span><span><strong>Cybersecurity</strong> protection</span><span><strong>Field IT</strong> across France</span></div></div>
</section>

<section class="ya-section ya-services-section"><div class="ya-shell"><div class="ya-section-head reveal"><span class="ya-kicker"><?php echo esc_html(ya_t('services')); ?></span><h2><?php echo esc_html(ya_t('services_title')); ?></h2><p><?php echo esc_html(ya_t('services_intro')); ?></p></div><div class="ya-card-grid ya-services-grid">
<?php $services=[['headset','Support informatique','Assistance L1/L2 sur site et à distance, postes, logiciels, imprimantes et incidents utilisateurs.','support'],['network-wired','Réseaux & Wi‑Fi','Installation et optimisation Wi‑Fi, switches, routeurs, VLAN, pare-feu et connectivité.','network'],['shield-halved','Cybersécurité','Protection des postes, comptes, accès, sauvegardes et réseaux professionnels.','security'],['cloud','Microsoft 365 & Cloud','Exchange, Teams, OneDrive, SharePoint, comptes, migrations et accompagnement cloud.','cloud'],['server','Infrastructure IT','Déploiement, maintenance, périphériques, postes, serveurs et environnements professionnels.','infra'],['lightbulb','Conseil & accompagnement','Audit, recommandations, choix de solutions et amélioration des performances IT.','consult']]; foreach($services as $i=>$s): ?>
<article class="ya-premium-card reveal" style="--delay:<?php echo esc_attr($i*55); ?>ms"><div class="ya-card-icon"><i class="fa-solid fa-<?php echo esc_attr($s[0]); ?>"></i></div><h3><?php echo esc_html($s[1]); ?></h3><p><?php echo esc_html($s[2]); ?></p><a href="<?php echo esc_url(ya_page('services').'#'.$s[3]); ?>"><?php echo esc_html(ya_t('readmore')); ?><i class="fa-solid fa-arrow-right"></i></a></article>
<?php endforeach; ?></div></div></section>

<section class="ya-dark-feature"><div class="ya-shell ya-split"><div class="reveal"><span class="ya-kicker"><?php echo esc_html(ya_t('why')); ?></span><h2><?php echo esc_html(ya_t('why_title')); ?></h2><p>Une approche terrain, structurée et orientée résultat pour maintenir vos utilisateurs, vos équipements et votre infrastructure opérationnels.</p><div class="ya-actions"><a class="ya-btn" href="<?php echo esc_url(ya_page('contact')); ?>"><?php echo esc_html(ya_t('contact')); ?></a><a class="ya-text-link" href="<?php echo esc_url(ya_page('projets')); ?>">Voir les expériences <i class="fa-solid fa-arrow-right"></i></a></div></div><div class="ya-stat-grid"><div class="reveal"><strong>120+</strong><span>Interventions</span></div><div class="reveal"><strong>6</strong><span>Domaines IT</span></div><div class="reveal"><strong>3+</strong><span>Années en France</span></div><div class="reveal"><strong>24h</strong><span>Réponse rapide</span></div></div></div></section>

<section class="ya-section"><div class="ya-shell"><div class="ya-section-head reveal"><span class="ya-kicker">TECHNOLOGIES & EXPERTISE</span><h2>Un environnement technique adapté aux entreprises</h2><p>Des technologies courantes en environnement professionnel, intégrées dans une approche orientée stabilité, sécurité et exploitation.</p></div><div class="ya-tech-grid"><?php foreach(['Microsoft 365'=>'microsoft','Azure'=>'cloud','Windows'=>'windows','Cisco'=>'network-wired','Fortinet'=>'shield-halved','VMware'=>'server','Ubiquiti'=>'wifi','Apple macOS'=>'apple','Linux'=>'linux','Dell'=>'laptop','HP'=>'print','Lenovo'=>'computer'] as $name=>$icon): ?><div class="ya-tech-chip reveal"><i class="fa-<?php echo in_array($icon,['apple','windows','linux'])?'brands':'solid'; ?> fa-<?php echo esc_attr($icon); ?>"></i><span><?php echo esc_html($name); ?></span></div><?php endforeach; ?></div></div></section>

<section class="ya-section ya-project-section"><div class="ya-shell"><div class="ya-section-head reveal"><span class="ya-kicker">RÉFÉRENCES PROFESSIONNELLES</span><h2>Expériences dans des environnements IT exigeants</h2><p>Des missions terrain et support réalisées dans différents environnements professionnels et industriels.</p></div><div class="ya-card-grid ya-project-grid"><?php $projects=[['Marelli','Châtellerault, France','Support informatique L1/L2, Microsoft 365, postes de travail et environnement industriel.'],['Action Logistics','Angers, France','Assistance technique, support réseau, préparation de postes et accompagnement sur site.'],['HCL Technologies','Enterprise IT','Support technique, résolution d’incidents et assistance utilisateurs.'],['TECEZE','Field IT Services','Interventions terrain, diagnostic, remplacement matériel et support infrastructure.'],['Cognizant','Enterprise IT','Assistance utilisateurs, maintenance des postes et accompagnement technique.'],['Wipro','Professional IT','Support utilisateurs, gestion d’incidents et assistance technique.']]; foreach($projects as $i=>$p): ?><article class="ya-project-card reveal"><span class="ya-mini-label">MISSION IT</span><h3><?php echo esc_html($p[0]); ?></h3><small><?php echo esc_html($p[1]); ?></small><p><?php echo esc_html($p[2]); ?></p><div class="ya-project-arrow"><i class="fa-solid fa-arrow-up-right-from-square"></i></div></article><?php endforeach; ?></div><p class="ya-disclaimer">Les références ci-dessus représentent des expériences et missions professionnelles réalisées dans différents environnements IT. Elles ne constituent pas nécessairement une approbation officielle ou un partenariat commercial public avec les entreprises citées.</p></div></section>

<section class="ya-partner-band"><div class="ya-shell"><div class="ya-partner-title"><span class="ya-kicker">ENVIRONNEMENTS & TECHNOLOGIES</span><p>Expérience au contact d’équipes, plateformes et environnements professionnels variés.</p></div></div><div class="ya-marquee" aria-label="Professional environments"><div class="ya-marquee-track"><?php $brands=['MARELLI','ACTION','HCLTECH','TECEZE','COGNIZANT','WIPRO','MICROSOFT','CISCO','FORTINET','UBIQUITI']; for($r=0;$r<2;$r++): foreach($brands as $b): ?><span class="ya-partner-logo"><?php echo esc_html($b); ?></span><?php endforeach; endfor; ?></div></div></section>

<?php $q=new WP_Query(['post_type'=>'post','posts_per_page'=>3,'post_status'=>'publish']); if($q->have_posts()): ?><section class="ya-section"><div class="ya-shell"><div class="ya-section-head reveal"><span class="ya-kicker">BLOG</span><h2><?php echo esc_html(ya_t('latest')); ?></h2><p><?php echo esc_html(ya_t('latest_intro')); ?></p></div><div class="ya-post-grid"><?php while($q->have_posts()):$q->the_post(); ?><article class="ya-post-card reveal"><?php if(has_post_thumbnail()): ?><a class="ya-post-image" href="<?php the_permalink(); ?>"><?php the_post_thumbnail('large'); ?><span></span></a><?php endif; ?><div class="ya-post-body"><small><?php echo esc_html(get_the_date()); ?></small><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),22)); ?></p><a class="ya-text-link" href="<?php the_permalink(); ?>"><?php echo esc_html(ya_t('readmore')); ?><i class="fa-solid fa-arrow-right"></i></a></div></article><?php endwhile; wp_reset_postdata(); ?></div></div></section><?php endif; ?>

<section class="ya-cta"><div class="ya-shell ya-cta-in reveal"><div><span class="ya-kicker">CONTACT</span><h2><?php echo esc_html(ya_t('cta_title')); ?></h2><p><?php echo esc_html(ya_t('cta_text')); ?></p></div><a class="ya-btn" href="<?php echo esc_url(ya_page('demander-un-devis')); ?>"><?php echo esc_html(ya_t('quote')); ?></a></div></section>
<?php get_footer(); ?>
