<?php
get_header();
while(have_posts()): the_post();
$slug = get_post_field('post_name');
$title = get_the_title();
$premium = ['a-propos','services','solutions','projets','contact','demander-un-devis'];
$hero_map = [
 'a-propos'=>['À PROPOS','Des services IT construits autour de la fiabilité.','Une approche professionnelle, terrain et orientée résultat pour accompagner les entreprises dans leurs opérations informatiques.','fa-user-gear'],
 'services'=>['SERVICES','Un support IT complet, du poste utilisateur à l’infrastructure.','Support, réseau, cybersécurité, Microsoft 365, cloud et interventions terrain avec une approche claire et structurée.','fa-layer-group'],
 'solutions'=>['SOLUTIONS','Des solutions IT pensées pour vos opérations quotidiennes.','Modern Workplace, réseaux sécurisés, exploitation IT et accompagnement technique pour des environnements plus stables.','fa-diagram-project'],
 'projets'=>['EXPÉRIENCES','Des interventions dans des environnements IT exigeants.','Support, déploiement, réseau et infrastructure réalisés dans différents contextes professionnels et industriels.','fa-briefcase'],
 'contact'=>['CONTACT','Parlons de votre besoin informatique.','Décrivez votre environnement, votre incident ou votre projet. Vous recevez une réponse claire et professionnelle.','fa-comments'],
 'demander-un-devis'=>['DEVIS','Recevez une réponse claire pour votre besoin IT.','Indiquez le contexte, le lieu, le périmètre et les contraintes de votre intervention pour faciliter l’évaluation.','fa-file-signature'],
];
if(in_array($slug,$premium,true)):
$hero=$hero_map[$slug]; ?>
<section class="ya-inner-hero"><div class="ya-inner-grid"></div><div class="ya-shell ya-inner-hero-in"><div class="reveal"><span class="ya-kicker"><?php echo esc_html($hero[0]); ?></span><h1><?php echo esc_html($hero[1]); ?></h1><p><?php echo esc_html($hero[2]); ?></p><div class="ya-inner-badges"><span><i class="fa-solid fa-circle-check"></i> Professionnel</span><span><i class="fa-solid fa-location-dot"></i> France</span><span><i class="fa-solid fa-shield-halved"></i> IT & sécurité</span></div></div><div class="ya-inner-visual reveal"><div class="ya-inner-icon"><i class="fa-solid <?php echo esc_attr($hero[3]); ?>"></i></div><div class="ya-inner-orbit"><i class="fa-solid fa-wifi"></i><i class="fa-solid fa-cloud"></i><i class="fa-solid fa-server"></i></div></div></div></section>
<?php if($slug==='services'): ?>
<section class="ya-section"><div class="ya-shell"><div class="ya-section-head reveal"><span class="ya-kicker">6 DOMAINES IT</span><h2>Des services conçus pour maintenir votre environnement opérationnel</h2><p>Des interventions ciblées, sur site ou à distance, avec une communication claire avant, pendant et après la mission.</p></div><div class="ya-card-grid ya-services-grid"><?php $items=[['support','headset','Support informatique','Postes Windows/macOS, incidents utilisateurs, logiciels, imprimantes, périphériques et assistance L1/L2.'],['network','network-wired','Réseaux & Wi‑Fi','Wi‑Fi professionnel, switches, routeurs, VLAN, DNS, connectivité et diagnostic réseau.'],['security','shield-halved','Cybersécurité','Protection des postes, accès, comptes, sauvegardes, firewall et bonnes pratiques de sécurité.'],['cloud','cloud','Microsoft 365 & Cloud','Microsoft 365, Teams, OneDrive, SharePoint, comptes, migrations et accompagnement utilisateur.'],['infra','server','Infrastructure IT','Déploiement, inventaire, maintenance, postes, serveurs, rack, périphériques et documentation.'],['consult','lightbulb','Conseil & accompagnement','Audit, recommandations, préparation de projet, choix de solutions et amélioration continue.']]; foreach($items as $i=>$it): ?><article id="<?php echo esc_attr($it[0]); ?>" class="ya-premium-card ya-service-detail reveal"><div class="ya-card-icon"><i class="fa-solid fa-<?php echo esc_attr($it[1]); ?>"></i></div><h3><?php echo esc_html($it[2]); ?></h3><p><?php echo esc_html($it[3]); ?></p><ul><li>Analyse du besoin</li><li>Intervention structurée</li><li>Validation et compte rendu</li></ul></article><?php endforeach; ?></div></div></section>
<section class="ya-dark-feature"><div class="ya-shell"><div class="ya-section-head ya-section-head-light reveal"><span class="ya-kicker">MÉTHODE</span><h2>Une intervention simple, lisible et professionnelle</h2></div><div class="ya-process-grid"><?php foreach([['1','Qualification','Compréhension du besoin, du site et du niveau d’urgence.'],['2','Préparation','Planification, prérequis techniques et coordination.'],['3','Intervention','Exécution méthodique avec communication pendant la mission.'],['4','Validation','Tests, compte rendu et recommandations de suivi.']] as $p): ?><div class="ya-process-card reveal"><b><?php echo esc_html($p[0]); ?></b><h3><?php echo esc_html($p[1]); ?></h3><p><?php echo esc_html($p[2]); ?></p></div><?php endforeach; ?></div></div></section>
<?php elseif($slug==='solutions'): ?>
<section class="ya-section"><div class="ya-shell"><div class="ya-solution-stack"><?php foreach([['Modern Workplace','Microsoft 365, Teams, OneDrive, identité, sécurité et collaboration.','fa-cloud','Microsoft 365 • Teams • OneDrive'],['Secure Network','Wi‑Fi professionnel, segmentation, firewall, VPN et performance réseau.','fa-shield-halved','Wi‑Fi • VLAN • Firewall • VPN'],['IT Operations','Support utilisateurs, déploiement, maintenance et documentation.','fa-gears','L1/L2 • Devices • Deployment'],['Field Services','Hands & eyes, remplacement matériel, réseau, rack et interventions multi-sites.','fa-location-crosshairs','On-site • Remote hands • Multi-site']] as $i=>$s): ?><article class="ya-solution-row reveal"><div class="ya-solution-icon"><i class="fa-solid <?php echo esc_attr($s[2]); ?>"></i></div><div><span class="ya-mini-label">SOLUTION <?php echo esc_html($i+1); ?></span><h2><?php echo esc_html($s[0]); ?></h2><p><?php echo esc_html($s[1]); ?></p><small><?php echo esc_html($s[3]); ?></small></div><a href="<?php echo esc_url(ya_page('contact')); ?>" class="ya-circle-link"><i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?></div></div></section>
<?php elseif($slug==='projets'): ?>
<section class="ya-section"><div class="ya-shell"><div class="ya-card-grid ya-project-grid"><?php foreach([['Marelli','Châtellerault, France','Support L1/L2, Microsoft 365, postes et environnement industriel.'],['Action Logistics','Angers / Moissy','Support terrain, réseau, préparation de postes et opérations logistiques.'],['HCL Technologies','Enterprise IT','Résolution d’incidents et assistance utilisateurs.'],['TECEZE','Field Services','Diagnostic, remplacement matériel et support infrastructure.'],['Cognizant','Enterprise IT','Maintenance postes, utilisateurs et support technique.'],['Wipro','Professional IT','Support utilisateurs, incidents et assistance terrain.']] as $p): ?><article class="ya-project-card reveal"><span class="ya-mini-label">MISSION IT</span><h3><?php echo esc_html($p[0]); ?></h3><small><?php echo esc_html($p[1]); ?></small><p><?php echo esc_html($p[2]); ?></p><div class="ya-project-arrow"><i class="fa-solid fa-arrow-up-right-from-square"></i></div></article><?php endforeach; ?></div><p class="ya-disclaimer">Ces références décrivent des expériences professionnelles et ne constituent pas nécessairement une approbation officielle ou un partenariat commercial public.</p></div></section>
<section class="ya-partner-band"><div class="ya-marquee"><div class="ya-marquee-track"><?php $brands=['MARELLI','ACTION','HCLTECH','TECEZE','COGNIZANT','WIPRO','MICROSOFT','CISCO','FORTINET','UBIQUITI']; for($r=0;$r<2;$r++): foreach($brands as $b): ?><span class="ya-partner-logo"><?php echo esc_html($b); ?></span><?php endforeach; endfor; ?></div></div></section>
<?php elseif($slug==='a-propos'): ?>
<section class="ya-section"><div class="ya-shell ya-about-grid"><div class="reveal"><span class="ya-kicker">NOTRE APPROCHE</span><h2>Une prestation IT basée sur la clarté, la préparation et le résultat.</h2><p>Yama Ahmadi Services Informatiques accompagne les entreprises pour leurs besoins de support, réseau, cybersécurité, Microsoft 365, infrastructure et interventions terrain.</p><p>L’objectif est simple : comprendre rapidement le contexte, intervenir de manière structurée, communiquer clairement et valider le résultat avant clôture.</p><a class="ya-btn" href="<?php echo esc_url(ya_page('contact')); ?>">Parler de votre besoin</a></div><div class="ya-value-grid"><?php foreach([['fa-bolt','Réactivité','Une communication rapide selon disponibilité et urgence.'],['fa-list-check','Méthode','Préparation, exécution, tests et compte rendu.'],['fa-shield-halved','Fiabilité','Des actions orientées stabilité et réduction du risque.'],['fa-language','Communication','Français et anglais pour faciliter les missions internationales.']] as $v): ?><div class="ya-value-card reveal"><i class="fa-solid <?php echo esc_attr($v[0]); ?>"></i><h3><?php echo esc_html($v[1]); ?></h3><p><?php echo esc_html($v[2]); ?></p></div><?php endforeach; ?></div></div></section>
<section class="ya-dark-feature"><div class="ya-shell ya-split"><div class="reveal"><span class="ya-kicker">CAPACITÉS</span><h2>Support terrain et assistance à distance</h2><p>Une combinaison de support utilisateur, réseau, infrastructure et coordination à distance pour répondre aux besoins multi-sites.</p></div><div class="ya-stat-grid"><div><strong>FR</strong><span>France</span></div><div><strong>EN</strong><span>English support</span></div><div><strong>L1/L2</strong><span>User support</span></div><div><strong>On-site</strong><span>Field services</span></div></div></div></section>
<?php elseif($slug==='contact' || $slug==='demander-un-devis'): ?>
<section class="ya-section"><div class="ya-shell ya-contact-layout"><aside class="ya-contact-panel reveal"><span class="ya-kicker">CONTACT DIRECT</span><h2><?php echo $slug==='demander-un-devis'?'Préparez votre demande':'Nous sommes à votre écoute'; ?></h2><p>Plus vous partagez de contexte, plus la réponse peut être précise.</p><div class="ya-contact-lines"><a href="tel:<?php echo esc_attr(preg_replace('/\s+/', '', get_theme_mod('ya_phone','+33 7 84 20 31 50'))); ?>"><i class="fa-solid fa-phone"></i><span><small>Téléphone</small><?php echo esc_html(get_theme_mod('ya_phone','+33 7 84 20 31 50')); ?></span></a><a href="mailto:<?php echo esc_attr(get_theme_mod('ya_email','support@yamaahmadi.fr')); ?>"><i class="fa-regular fa-envelope"></i><span><small>E-mail</small><?php echo esc_html(get_theme_mod('ya_email','support@yamaahmadi.fr')); ?></span></a><div><i class="fa-solid fa-location-dot"></i><span><small>Zone</small><?php echo esc_html(get_theme_mod('ya_location','France')); ?></span></div><div><i class="fa-regular fa-clock"></i><span><small>Disponibilité</small><?php echo esc_html(get_theme_mod('ya_hours','Lun – Ven : 08:00 – 18:00')); ?></span></div></div><div class="ya-contact-note"><i class="fa-solid fa-shield-halved"></i><span>Les informations envoyées sont utilisées uniquement pour traiter votre demande.</span></div></aside><div class="ya-form-card reveal"><span class="ya-kicker"><?php echo $slug==='demander-un-devis'?'DEMANDE DE DEVIS':'MESSAGE'; ?></span><h2><?php echo $slug==='demander-un-devis'?'Décrivez votre besoin':'Envoyez votre demande'; ?></h2><?php $raw_content=get_the_content(); $ff=''; if(preg_match('/\[fluentform[^\]]*id=[\"\']?(\d+)[\"\']?[^\]]*\]/i',$raw_content,$m)){ $ff='[fluentform id="'.intval($m[1]).'"]'; } if(!$ff){$ff='[fluentform id="1"]';} ?><div class="ya-existing-form"><?php echo do_shortcode($ff); ?></div></div></div></section>
<?php endif; ?>
<section class="ya-cta"><div class="ya-shell ya-cta-in reveal"><div><span class="ya-kicker">NEXT STEP</span><h2>Besoin d’un environnement IT plus fiable ?</h2><p>Parlons du contexte et identifions la prochaine action utile.</p></div><a class="ya-btn" href="<?php echo esc_url(ya_page('demander-un-devis')); ?>"><?php echo esc_html(ya_t('quote')); ?></a></div></section>
<?php else: ?>
<section class="ya-inner-hero ya-inner-hero-compact"><div class="ya-inner-grid"></div><div class="ya-shell"><span class="ya-kicker">YAMA AHMADI IT SERVICES</span><h1><?php echo esc_html($title); ?></h1></div></section><section class="ya-page"><div class="ya-shell ya-prose"><?php the_content(); ?></div></section>
<?php endif; endwhile; get_footer(); ?>
